# Generated by Django 4.2.6 on 2023-10-19 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jop_title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='FindJops')),
                ('company_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('jop_nature', models.CharField(choices=[('Full_time', 'Full_time'), ('Part_time', 'Part_time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=10)),
            ],
        ),
    ]
